apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infra-manager
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - services
      - configmaps
    verbs:
      - create
      - get
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - update
      - delete
