resources:
- namespace.yaml
- certgen-job.yaml
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: envoy-gateway-config
  files:
  - envoy-gateway.yaml
